version: "3.8"

services:
  client:
    env_file:
      - .env
    build:
      context: "."
      dockerfile: Dockerfile
    container_name: spaceinvaders-server
    command: yarn dev
    ports:
      - "8080:8080"
    volumes:
      - ./:/app/
